### ISSUE TITLE
update react-native dependency for supporting 0.6-RC

### ISSUE THREAD

**Issue by chirag04** [naoufal/react-native-activity-view#3]
Right now the dependency of 0.4.4 creates a new react-native install inside activity-view. Change it to 0.5 so that it works with both 0.5 and 0.6 without install react-native again inside activity-view.

https://github.com/chirag04/react-native-dashed-border/blob/master/package.json#L24-L26

**Comment by naoufal** [comment]
Thanks for the notice @chirag04.

I actually came across this issue on [react-native-accordion](https://github.com/naoufal/react-native-accordion) too and using `>=0.4.0` turns out to be a better solution since it covers `0.4.0`, `0.5.0` and `0.6.0`.

![screen shot 2015-06-18 at 12 00 07 pm](https://cloud.githubusercontent.com/assets/1627824/8235739/a6a3f544-15b1-11e5-9ad4-374194f9582c.png)

I'll get that out in bit.

**Comment by chirag04** [comment]
Sweet. Thanks. Is 0.2.1 published to npm?

**Comment by naoufal** [comment]
Yeah, it should propagate soon enough.
