### ISSUE TITLE
merge with react-native-social-share?

### ISSUE THREAD

**Issue by chirag04** [naoufal/react-native-activity-view#5]
Code is very much the same and provides the same feature. It would be awesome if we can merge the two projects.

I was hoping to get react-native-social-share merged into activity-view.

@naoufal  What do you think? I can PR.

**Comment by naoufal** [comment]
@chriag I'm not sure I agree with this.  

Even if the code is similar, I'd rather have this module focus on interactions between the activity view and activities.  I can see where you're coming from and it's something I considered as well since the functions exposed in `react-native-social-share` are after all built-in activities.  But I feel like including them in this module is outside the scope of the activity view.

That said, I am interested in exploring another option to expose them.

When creating this module I started work on another module that helps define custom activities.  It could be interesting to have that module expose built-in activities (share to twitter, facebook or print) directly.

How does that sound?

**Comment by chirag04** [comment]
That could be interesting. Is the module for custom activity open sourced? can you link it here. I can def. use that module if you can expose built-in activities.

**Comment by naoufal** [comment]
@chirag04 it isn't yet.  But I can share it out when basic functionality is complete.  I can probably get around to that when returning from vacation.

**Comment by chirag04** [comment]
Cool. No problem. Looking forward to that module. Enjoy your vacation :)

**Comment by naoufal** [comment]
Thanks.  Closing this issue for now.
